version: '3'

services:

  web:
    build: ./web
    expose:
      - 8000
    volumes:
      - ./web:/home/app/xpinnit_api/web/
      - web-static:/home/app/xpinnit_api/web/static/
    env_file:
      - ./.env.prod
    command: gunicorn docker_django.wsgi:application -w 2 --bind 0.0.0:8000
    networks:
      - proxy

  nginx-proxy:
    restart: always
    container_name: nginx-proxy
    build: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - web-static:/www/static
      - media_volume:/www/media
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
    networks:
      - proxy

  nginx-proxy-gen:
    container_name: nginx-proxy-gen
    image: nginxproxy/docker-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - conf:/etc/nginx/conf.d

  nginx-proxy-letsencrypt:
    image: nginxproxy/acme-companion
    env_file:
      - .env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./mongo/.env.prod
    networks:
      - proxy

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./mongo-express/.env.prod
    networks:
      - proxy

  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    networks:
      - proxy

  celery:
    build: ./web
    command: celery -A docker_django worker -l info
    env_file:
      - ./.env.prod
    volumes:
      - ./web:/home/app/xpinnit_api/web/
      - celerydata:/usr/src/app/
    depends_on:
      - redis
    networks:
      - proxy

volumes:
  web-static:
  acme:
  redisdata:
  html:
  vhost:
  conf:
  media_volume:
  certs:
  celerydata:

networks:
  proxy:
    external:
      name: nginx-proxy
